=== aronk/flightschedule-business-event/docs/flight-schedule-data-event.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Flight Schedule Data Event Schema",
  "description": "Flight schedule data change event stream",
  "type": "object",
  "properties": {
    "flightScheduleId": {
      "description": "The unique identifier for a flight schedule",
      "type": "integer"
    },
    "flightNumber": {
      "description": "The flight number",
      "type": "string"
    },
    "departureDate": {
      "description": "The flight departure date",
      "type": "string",
      "format": "date"
    },
    "scheduledDepartureTime": {
      "description": "The flight scheduled departure time",
      "type": "string",
      "format": "date-time"
    },
    "estimatedDepartureTime": {
      "description": "The flight estimated departure time",
      "type": "string",
      "format": "date-time"
    },
    "originPort": {
      "description": "The flight origin port",
      "type": "string"
    },
    "originCountry": {
      "description": "The flight origin country",
      "type": "string"
    },
    "destinationPort": {
      "description": "The flight destination port",
      "type": "string"
    },
    "destinationCountry": {
      "description": "The flight destination country",
      "type": "string"
    },
    "airline": {
      "description": "The airline code",
      "type": "string"
    }
  },
  "required": [
    "flightScheduleId",
    "flightNumber",
    "departureDate",
    "scheduledDepartureTime",
    "estimatedDepartureTime",
    "originPort",
    "originCountry",
    "destinationPort",
    "destinationCountry",
    "airline"
  ]
}

=== aronk/flightschedule-business-event/docs/flight-schedule-data-event-002.json
{
  "flightScheduleId": 12345678,
  "flightNumber": "QF425",
  "departureDate": "2019-10-16",
  "scheduledDepartureTime": "2019-10-16T06:10:39.000Z",
  "estimatedDepartureTime": "2019-10-16T06:30:59.000Z",
  "originPort": "Sydney",
  "originCountry": "Australia",
  "destinationPort": "Melbourne",
  "destinationCountry": "Australia",
  "airline": "QF"
}

=== aronk/flightschedule-business-event/docs/flight-schedule-data-event.json
{
  "flightScheduleId": 12345678,
  "flightNumber": "QF425",
  "departureDate": "2019-10-16",
  "scheduledDepartureTime": "2019-10-16T06:10:39+00:00",
  "estimatedDepartureTime": "2019-10-16T06:20:59+00:00",
  "originPort": "Sydney",
  "originCountry": "Australia",
  "destinationPort": "Melbourne",
  "destinationCountry": "Australia",
  "airline": "QF"
}
